// TextFormatterNode - Simple text formatting for backward compatibility

const { Node } = require('brainyflow')
const { debugLog, deduplicateUrls } = require('../utils')

class TextFormatterNode extends Node {
  async prep (memory) {
    const { summary, options } = memory

    if (!summary) {
      throw new Error('TextFormatterNode: summary is required')
    }

    debugLog(
      '📝 TextFormatterNode: Formatting text output...',
      'text-format-start',
      options.debug ? memory.debugSteps : null
    )

    return { summary, options }
  }

  async exec ({ summary, options }) {
    // For simple flows, the summary might already be generated by SummaryGeneration
    // This node just ensures proper formatting and deduplication
    return summary
  }

  async post (memory, prepResult, execResult) {
    let formattedSummary = execResult
    const { options } = memory

    // Post-process to remove duplicate URLs
    const { cleanedText, duplicatesRemoved } = deduplicateUrls(formattedSummary)
    formattedSummary = cleanedText

    // Store final summary in memory
    memory.summary = formattedSummary

    debugLog(
      `✅ TextFormatterNode: Text formatting complete. Removed ${duplicatesRemoved} duplicate URLs`,
      'text-format-complete',
      options.debug ? memory.debugSteps : null
    )

    // Update metadata
    if (!memory.metadata) {
      memory.metadata = {}
    }
    memory.metadata.duplicateUrlsRemoved = duplicatesRemoved
  }
}

module.exports = TextFormatterNode
